<script setup lang="ts">
</script>
<template>
  <div>
    <div class="text-theme-sub-content">
      Bearer authentication (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. The name “Bearer authentication” can be understood as “give access to the bearer of this token.” The bearer token is a cryptic string, usually generated by the server in response to a login request. The client must send this token in the Authorization header when making requests to protected resources:
    </div>
    <pre
      style="background-color: rgb(251, 251, 251);"
      class="border border-solid rounded border-theme-text-box max-h-70 overflow-y-auto py-2.5 px-3.5 mt-2.5 flex items-start whitespace-pre-wrap break-all">
        <code>Authorization: Bearer &lt;token&gt;</code>
      </pre>
  </div>
</template>
<style scoped>
.ant-tag {
  margin-right: 0;
  line-height: 18px;
}
</style>
