CREATE TABLE `exec_sample`
(
    `id`                        bigint(20) NOT NULL,
    `exec_id`                   bigint(20) NOT NULL,
    `node_id`                   bigint(20) NOT NULL,
    `tenant_id`                 bigint(20) NOT NULL,
    `finish`                    bit(1)       NOT NULL,
    `timestamp`                 bigint(20) NOT NULL,
    `timestamp0`                bigint(20) NOT NULL,
    `name`                      varchar(400) NOT NULL,
    `ramp_num`                  int(11) DEFAULT 1,
    `duration`                  bigint(20) DEFAULT NULL,
    `duration0`                 bigint(20) DEFAULT NULL,
    `start_time`                bigint(20) DEFAULT NULL,
    `end_time`                  bigint(20) DEFAULT NULL,
    `errors`                    bigint(20) DEFAULT NULL,
    `iterations`                bigint(20) DEFAULT NULL,
    `n`                         bigint(20) DEFAULT NULL,
    `operations`                bigint(20) DEFAULT NULL,
    `transactions`              bigint(20) DEFAULT NULL,
    `read_bytes`                bigint(20) DEFAULT NULL,
    `write_bytes`               bigint(20) DEFAULT NULL,
    `ops` double DEFAULT NULL,
    `tps` double DEFAULT NULL,
    `brps` double DEFAULT NULL,
    `bwps` double DEFAULT NULL,
    `tran_mean` double DEFAULT NULL,
    `tran_min` double DEFAULT NULL,
    `tran_max` double DEFAULT NULL,
    `tran_p50` double DEFAULT NULL,
    `tran_p75` double DEFAULT NULL,
    `tran_p90` double DEFAULT NULL,
    `tran_p95` double DEFAULT NULL,
    `tran_p99` double DEFAULT NULL,
    `tran_p999` double DEFAULT NULL,
    `error_rate` double DEFAULT NULL,
    `error_cause_counter`       json   DEFAULT NULL,
    `thread_pool_size`          int(10) DEFAULT NULL,
    `thread_pool_active_size`   int(10) DEFAULT NULL,
    `thread_max_pool_size`      int(10) DEFAULT NULL,
    `thread_running`            bit(1) DEFAULT NULL,
    `thread_terminated`         bit(1) DEFAULT NULL,
    `upload_result_bytes`       bigint(20) DEFAULT NULL,
    `upload_result_total_bytes` bigint(20) DEFAULT NULL,
    `ext_counter_map1`          json   DEFAULT NULL,
    `ext_counter_map2`          json   DEFAULT NULL,
    `ext_counter1`              bigint(20) DEFAULT NULL,
    `ext_counter2`              bigint(20) DEFAULT NULL,
    `ext_gauge1` double DEFAULT NULL,
    `ext_gauge2` double DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE,
    INDEX                       `idx_exec_id` (`exec_id`) USING BTREE,
    INDEX                       `idx_node_id` (`node_id`) USING BTREE,
    #INDEX                      `idx_tenant_id` (`tenant_id`) USING BTREE,
    INDEX                       `idx_timestamp` (`timestamp`) USING BTREE,
    INDEX                       `idx_name` (`name`) USING BTREE,
    INDEX                       `idx_ramp_num` (`ramp_num`) USING BTREE,
    INDEX                       `idx_finish` (`finish`) USING BTREE
) ENGINE = InnoDB;
