import { PUB_TESTER, TESTER } from '@xcan-angus/infra';

import Activity from './Activity';
import Apis from './Apis';
import Services from './Services';
import Mock from './Mock';
import Project from './Project';
import Analysis from './Analysis';
import Indicator from './Indicator';
import Variable from './Variable';
import Node from './Node';
import Scenario from './Scenario';
import Script from './Script';
import AngusScript from './AngusScript';
import Issue from './Issue';
import ShareApis from './ShareApis';
import Exec from './Exec';
import Kanban from './Kanban';
import DataSource from './DataSource';
import DataSet from './DataSet';
import Module from './Module';
import Software from './Software';
import ParamTarget from './ParamTarget';
import Report from './Report';
import Tag from './Tag';
import Test from './Test';
import TestPlan from './TestPlan';
import TestCase from './TestCase';
import TestTemplate from './TestTemplate';
import Evaluation from './Evaluation';

const baseUrl = TESTER;
const pubBaseUrl = PUB_TESTER;

export const activity = new Activity(baseUrl);
export const apis = new Apis(baseUrl);
export const services = new Services(baseUrl);
export const mock = new Mock(baseUrl);
export const project = new Project(baseUrl);
export const analysis = new Analysis(baseUrl);
export const indicator = new Indicator(baseUrl);
export const variable = new Variable(baseUrl);
export const node = new Node(baseUrl);
export const scenario = new Scenario(baseUrl);
export const script = new Script(baseUrl);
export const angusScript = new AngusScript(baseUrl);
export const issue = new Issue(baseUrl);
export const shareApis = new ShareApis(pubBaseUrl);
export const exec = new Exec(baseUrl);
export const kanban = new Kanban(baseUrl);
export const datasource = new DataSource(baseUrl);
export const dataset = new DataSet(baseUrl);
export const modules = new Module(baseUrl);
export const software = new Software(baseUrl);
export const paramTarget = new ParamTarget(baseUrl);
export const report = new Report(baseUrl);
export const tag = new Tag(baseUrl);
export const test = new Test(baseUrl);
export const testPlan = new TestPlan(baseUrl);
export const testCase = new TestCase(baseUrl);
export const testTemplate = new TestTemplate(baseUrl);
export const evaluation = new Evaluation(baseUrl);
