import { EnumMessage, EvalWorkloadMethod, Priority, enumUtils } from '@xcan-angus/infra';
import { BugLevel, ExecResult, TaskStatus, TaskType, TestType, AssociateUserType } from '@/enums/enums';
import { AttachmentInfo, ProgressInfo, TagInfo } from '@/types/types';

import { CaseInfo } from '@/views/test/types';

/** Task type name mapping for UI display */
export const getTaskTypeName = () => {
  return enumUtils.enumToMap(TaskType);
};

/**
 * Task information interface containing all task-related data
 */
export type TaskInfo = {
  id: number;
  name: string;
  code: string;
  projectId: number;
  projectName: string;
  sprintId: number;
  sprintName: string;
  sprintAuth: boolean;
  moduleId: number;
  moduleName: string;
  backlog: boolean;
  priority: EnumMessage<Priority>;
  status: EnumMessage<TaskStatus>;
  progress: ProgressInfo;
  taskType: EnumMessage<TaskType>;
  bugLevel: EnumMessage<BugLevel>;
  testType: EnumMessage<TestType>;
  softwareVersion: string;
  startDate: string;
  deadlineDate: string;
  confirmedDate: string;
  canceledDate: string;
  completedDate: string;
  processedDate: string;
  assigneeId: number;
  assigneeName: string;
  assigneeAvatar: string;
  confirmerId: number;
  confirmerName: string;
  testerId: number;
  testerName: string;
  escapedBug: boolean;
  unplanned: boolean;
  parentTaskId: number;
  parentTaskName: string;
  evalWorkloadMethod: EnumMessage<EvalWorkloadMethod>;
  evalWorkload: number;
  actualWorkload: number;
  failNum: number;
  totalNum: number;
  attachments?: AttachmentInfo[] | undefined;
  description: string;
  currentAssociateType: EnumMessage<AssociateUserType>[];
  confirmTask: boolean;
  overdue: boolean;
  targetId: number;
  targetName: string;
  targetParentId: number;
  targetParentName: string;
  scriptId: number;
  scriptName: string;
  execResult: EnumMessage<ExecResult>;
  execFailureMessage: string;
  execTestNum: number;
  execTestFailureNum: number;
  execId: number;
  execName: string;
  execBy: string;
  execByName: string;
  execDate: string;
  favourite: boolean;
  follow: boolean;
  tags: TagInfo[];
  tenantId: number;
  createdBy: number;
  createdByName: string;
  createdDate: string;
  avatar: string;
  lastModifiedBy: number;
  lastModifiedByName: string;
  lastModifiedDate: string;
}

export type TaskDetail = {
  id: number;
  name: string;
  code: string;
  projectId: number;
  projectName: string;
  sprintId: number;
  sprintName: string;
  sprintAuth: boolean;
  moduleId: number;
  moduleName: string;
  backlog: boolean;
  priority: EnumMessage<Priority>;
  status: EnumMessage<TaskStatus>;
  progress: ProgressInfo | number;
  subTaskProgress: ProgressInfo;
  taskType: EnumMessage<TaskType>;
  bugLevel: EnumMessage<BugLevel>;
  testType: EnumMessage<TestType>;
  softwareVersion: string;
  startDate: string;
  deadlineDate: string;
  confirmedDate: string;
  canceledDate: string;
  completedDate: string;
  processedDate: string;
  assigneeId: number;
  assigneeName: string;
  assigneeAvatar: string;
  confirmerId: number;
  confirmerName: string;
  testerId: number;
  testerName: string;
  escapedBug: boolean;
  unplanned: boolean;
  parentTaskId: number;
  parentTaskName: string;
  evalWorkloadMethod: EnumMessage<EvalWorkloadMethod>;
  evalWorkload: number;
  actualWorkload: number;
  failNum: number;
  totalNum: number;
  attachments?: AttachmentInfo[] | undefined;
  description: string;
  currentAssociateType: EnumMessage<AssociateUserType>[];
  confirmTask: boolean;
  overdue: boolean;
  targetId: number;
  targetName: string;
  targetParentId: number;
  targetParentName: string;
  scriptId: number;
  scriptName: string;
  execResult: EnumMessage<ExecResult>;
  execFailureMessage: string;
  execTestNum: number;
  execTestFailureNum: number;
  execId: number;
  execName: string;
  execBy: number;
  execByName: string;
  execDate: string;
  favourite: boolean;
  follow: boolean;
  tags: TagInfo[];
  refTaskInfos: TaskInfo[];
  refCaseInfos: CaseInfo[];
  subTaskInfos: TaskInfo[];
  tenantId: number;
  createdBy: number;
  createdByName: string;
  createdDate: string;
  avatar: string;
  lastModifiedBy: number;
  lastModifiedByName: string;
  lastModifiedDate: string;
  linkUrl?: string
}
