package cloud.xcan.sdf.core.angustester.domain.kanban;

public enum DataAssetsLabel {
  TOTAL, PLAN, CASES, SERVICES, APIS, SCENARIO, SCRIPT, TASK_SPRINT, TASK,
  TEST_FUNCTIONALITY, TEST_PERFORMANCE, TEST_STABILITY, TEST_CUSTOMIZATION,
  MOCK_SERVICE, MOCK_APIS, MOCK_RESPONSE, MOCK_PUSHBACK,
  DATA_VARIABLE, DATA_DATASET, DATA_DATASOURCE/*, DATA_FILE*/,
  REPORT, REPORT_RECORD/*,
  EXECUTION, EXECUTION_DEBUG*/
}
